import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

export interface ReportData {
  workflowName: string;
  executedAt: string;
  executionTime: number;
  statistics: {
    totalElements: number;
    elementsByType: Record<string, number>;
    schema: string;
  };
  validations?: {
    passed: number;
    failed: number;
    details: Array<{
      rule: string;
      status: 'passed' | 'failed';
      message: string;
    }>;
  };
  logs: string[];
}

export async function generateWorkflowReport(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header con logo y título
    doc
      .fontSize(24)
      .fillColor('#7fb069')
      .text('DATAWiSE BIM Report', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(16)
      .fillColor('#333333')
      .text(data.workflowName, { align: 'center' })
      .moveDown(1);

    // Información de ejecución
    doc
      .fontSize(14)
      .fillColor('#7fb069')
      .text('Execution Information', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(11)
      .fillColor('#666666')
      .text(`Executed at: ${new Date(data.executedAt).toLocaleString('es-ES')}`)
      .text(`Execution time: ${data.executionTime.toFixed(2)}s`)
      .moveDown(1);

    // Estadísticas del modelo
    doc
      .fontSize(14)
      .fillColor('#7fb069')
      .text('Model Statistics', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(11)
      .fillColor('#666666')
      .text(`Schema: ${data.statistics.schema}`)
      .text(`Total elements: ${data.statistics.totalElements}`)
      .moveDown(0.5);

    // Elementos por tipo
    doc
      .fontSize(12)
      .fillColor('#333333')
      .text('Elements by type:', { underline: true })
      .moveDown(0.3);

    doc.fontSize(10).fillColor('#666666');
    Object.entries(data.statistics.elementsByType)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10) // Top 10 tipos
      .forEach(([type, count]) => {
        doc.text(`  • ${type}: ${count}`);
      });

    doc.moveDown(1);

    // Validaciones (si existen)
    if (data.validations) {
      doc
        .fontSize(14)
        .fillColor('#7fb069')
        .text('Validation Results', { underline: true })
        .moveDown(0.5);

      doc
        .fontSize(11)
        .fillColor('#666666')
        .text(`Passed: ${data.validations.passed}`)
        .fillColor('#d32f2f')
        .text(`Failed: ${data.validations.failed}`)
        .moveDown(0.5);

      if (data.validations.details.length > 0) {
        doc
          .fontSize(12)
          .fillColor('#333333')
          .text('Validation Details:', { underline: true })
          .moveDown(0.3);

        data.validations.details.slice(0, 15).forEach((detail) => {
          const color = detail.status === 'passed' ? '#4caf50' : '#d32f2f';
          doc
            .fontSize(10)
            .fillColor(color)
            .text(`  ${detail.status === 'passed' ? '✓' : '✗'} ${detail.rule}`, {
              continued: true,
            })
            .fillColor('#666666')
            .text(` - ${detail.message}`);
        });
      }

      doc.moveDown(1);
    }

    // Logs de ejecución
    if (data.logs.length > 0) {
      doc.addPage();
      doc
        .fontSize(14)
        .fillColor('#7fb069')
        .text('Execution Logs', { underline: true })
        .moveDown(0.5);

      doc.fontSize(9).fillColor('#666666');
      data.logs.slice(0, 50).forEach((log) => {
        doc.text(log);
      });
    }

    // Footer
    doc
      .fontSize(8)
      .fillColor('#999999')
      .text(
        `Generated by DATAWiSE BIM Digital Twin Platform - ${new Date().toLocaleDateString('es-ES')}`,
        50,
        doc.page.height - 50,
        { align: 'center' }
      );

    doc.end();
  });
}
